name: TeamGuild
version: 1.1.6
author: Himmelt
main: org.soraworld.guild.GuildPlugin
depend: [Violet]
softdepend: [Vault,Essentials,PlayerPoints,PlaceholderAPI,Residence]
website: https://github.com/Himmelt/TeamGuild
description: TeamGuild Plugin.
permissions:
  teamguild.admin:
    default: op
